export const YNAB_MILLIUNIT_CONVERSION = 1000;

export const MULTIPLIER_LOCAL_INDEPENDENT = 1.43;
export const MULTIPLIER_NATIONAL_CHAIN = 0.43;

export const TAX_RATE_BETTER_STREETS = 0.005;
export const TAX_RATE_REID_PARK_ZOO = 0.001;
export const TAX_RATE_GENERAL_FUND = 0.02;
